Refactor setupDDEV and installTYPO3

diff --git a/t3quickstart b/t3quickstart
--- a/t3quickstart
+++ b/t3quickstart
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-set -x
-set +e
+set -euo pipefail
 
 TYPO3_BASE_VERSION=
-TYPO3_PACKAGE_VERSION=
 PROJECT_NAME=
 
 ## Load Environment from .env File
@@ -16,24 +14,25 @@ loadEnv() {
   if [ -z "${PROJECT_NAME}" ]; then
     PROJECT_NAME="typo3-v${TYPO3_BASE_VERSION}"
   fi
-
-  #  [[ $TYPO3_BASE_VERSION == 10 ]] && TYPO3_CLI_COMMAND="typo3cms"
-
 }
 
 ## Create Project Directory
 createDirectory() {
-  mkdir -p ${PROJECT_NAME}
-  cd ${PROJECT_NAME} || exit
+  if [ -d "${PROJECT_NAME}" ]; then
+    echo "Directory ${PROJECT_NAME} already exists. Exiting."
+    exit 1
+  fi
+  mkdir -p "${PROJECT_NAME}"
+  cd "${PROJECT_NAME}" || exit
 }
 
 ## Setup ddev
 setupDDEV() {
   ddev config \
-    --project-name=${PROJECT_NAME} \
+    --project-name="${PROJECT_NAME}" \
     --webserver-type=apache-fpm \
-    --php-version=${PHP_VERSION} \
-    --database=${DATABASE_VERSION} \
+    --php-version="${PHP_VERSION}" \
+    --database="${DATABASE_VERSION}" \
     --project-type=typo3 \
     --docroot=public \
     --disable-settings-management=false \
@@ -42,32 +41,7 @@ setupDDEV() {
 
   ddev config --web-environment-add="COMPOSER_ROOT_VERSION=${COMPOSER_ROOT_VERSION}"
 
-  # Install phpMyadmin
   ddev add-on get ddev/ddev-phpmyadmin
-}
-
-## install TYPO3
-installTYPO3() {
-  ddev start -y
-  find . -name '.DS_Store' -delete
-  rm -f .DS_Store
-  ddev composer create --no-interaction typo3/cms-base-distribution:"^${TYPO3_VERSION}"
-
-  ddev composer config --no-interaction --unset platform
-
-  ## better Structure v11
-  # if [ ${TYPO3_BASE_VERSION} -eq 11 ]; then
-  #   echo 'Change cms-composer-installers for TYPO3 11'
-  #   ddev composer config allow-plugins.typo3/cms-composer-installers true
-  #   ddev composer require --no-interaction "typo3/cms-composer-installers:^4.0@rc"
-
-  #   echo 'Update for typo3-console'
-  #   ddev exec "sed -i 's/typo3cms install:fixfolderstructure/typo3 install:fixfolderstructure/g' composer.json"
-  # fi
-
-  if [ -n "${TYPO3_CONSOLE_VERSION}" ]; then
-    ddev composer require --no-interaction "helhum/typo3-console:^${TYPO3_CONSOLE_VERSION}"
-  fi
 }
 
 composerInstall() {
@@ -168,6 +142,9 @@ composerInstall() {
 setupTYPO3() {
   ddev config --auto
 
+  ## Drop and recreate database to ensure clean state
+  ddev exec "mysql -u root -proot -e 'DROP DATABASE IF EXISTS ${TYPO3_INSTALL_DB_DBNAME}; CREATE DATABASE ${TYPO3_INSTALL_DB_DBNAME};'"
+
   case $TYPO3_BASE_VERSION in
   10 | 11)
     ddev $TYPO3_CLI_COMMAND install:setup \
@@ -176,9 +153,9 @@ setupTYPO3() {
       --database-host-name="db" \
       --database-port="3306" \
       --database-socket="" \
-      --database-name="db" \
-      --database-user-name="db" \
-      --database-user-password="db" \
+      --database-name="${TYPO3_INSTALL_DB_DBNAME}" \
+      --database-user-name="${TYPO3_INSTALL_DB_USER}" \
+      --database-user-password="${TYPO3_INSTALL_DB_PASSWORD}" \
       --admin-user-name="${TYPO3_INSTALL_ADMIN_USER}" \
       --admin-password="${TYPO3_INSTALL_ADMIN_PASSWORD}" \
       --site-name="TYPO3 ${TYPO3_BASE_VERSION}" \
@@ -189,15 +166,13 @@ setupTYPO3() {
       --no-interaction
     ;;
   *)
-    # Tip: You may want to add the option --create-site="https://${PWD##*/}.ddev.site/"
-    # to create a site configuration independently of the initialization of my site package
     ddev $TYPO3_CLI_COMMAND setup \
       --driver="mysqli" \
       --host="db" \
       --port=3306 \
-      --dbname="db" \
-      --username="db" \
-      --password="db" \
+      --dbname="${TYPO3_INSTALL_DB_DBNAME}" \
+      --username="${TYPO3_INSTALL_DB_USER}" \
+      --password="${TYPO3_INSTALL_DB_PASSWORD}" \
       --admin-username="${TYPO3_INSTALL_ADMIN_USER}" \
       --admin-user-password="${TYPO3_INSTALL_ADMIN_PASSWORD}" \
       --admin-email="admin@ddev.site" \
@@ -226,23 +201,23 @@ installIntroductionPackage() {
   ddev composer require "typo3/cms-indexed-search:$TYPO3_PACKAGE_VERSION"
 }
 
-## Clean System
+## Upgrade System
 upgradeSystem() {
   ddev composer update
 
   ddev ${TYPO3_CLI_COMMAND} install:fixfolderstructure -nq
   ddev ${TYPO3_CLI_COMMAND} database:updateschema -nq
 
-  if [ "$TYPO3_CLI_COMMAND" = "typo3cms" ]; then
-    ddev typo3 upgrade:run -nq
+  case $TYPO3_BASE_VERSION in
+  10 | 11)
     ddev ${TYPO3_CLI_COMMAND} extension:setupactive -nq
-    ddev ${TYPO3_CLI_COMMAND} cache:flush -nq
-  else
-    ddev ${TYPO3_CLI_COMMAND} upgrade:run -nq
-    ddev ${TYPO3_CLI_COMMAND} install:extensionsetupifpossible -nq
-    ddev ${TYPO3_CLI_COMMAND} cache:flush -nq
-    ddev ${TYPO3_CLI_COMMAND} cache:warmup -nq
-  fi
+    ;;
+  *)
+    ddev ${TYPO3_CLI_COMMAND} extension:setup --no-interaction -nq
+    ;;
+  esac
+
+  ddev ${TYPO3_CLI_COMMAND} cache:flush -nq
 }
 
 showStatus() {
@@ -264,24 +239,23 @@ deleteProject() {
   fi
 
   # Change directory and perform ddev commands
-  if cd "$PROJECT_NAME"; then
+  if cd "${PROJECT_NAME}"; then
     ddev stop
     if ! ddev delete --omit-snapshot --yes; then
       echo "Failed to delete project with ddev. Exiting."
       exit 1
     fi
-    cd ..
   else
-    echo "Failed to change directory to $PROJECT_NAME. Exiting."
+    echo "Failed to change directory to ${PROJECT_NAME}. Exiting."
     exit 1
   fi
 
   # Delete the directory
-  if rm -rf "$PROJECT_NAME"; then
-    echo "Successfully deleted project directory $PROJECT_NAME."
+  if rm -rf "${PROJECT_NAME}"; then
+    echo "Successfully deleted project directory ${PROJECT_NAME}."
   else
-    echo "Failed to delete project directory $PROJECT_NAME."
-    rm -rf "$PROJECT_NAME"
+    echo "Failed to delete project directory ${PROJECT_NAME}."
+    exit 1
   fi
 }
 
